# Session 1: Python and NumPy

---
# Part 1: Python review


## 1.1 Data types

In [18]:
n_samples = 150
temperature = 36.6 
gene_name = "TP53" 
is_tumor = True 
missing_value = None 

for value in [n_samples, temperature, gene_name, is_tumor, missing_value]:
    print(repr(value), "->", type(value))

150 -> <class 'int'>
36.6 -> <class 'float'>
'TP53' -> <class 'str'>
True -> <class 'bool'>
None -> <class 'NoneType'>


## 1.2 Naming variables

PEP 8 says:

| What | Style | Example |
| --- | --- | --- |
| Variables and functions | `snake_case` | `n_samples`, `compute_gc_content` |
| Classes | `PascalCase` | `DNASequence`, `LinearRegression` |
| Constants | `UPPER_CASE` | `MAX_ITERATIONS` |

- **Be descriptive.** (`expression_matrix` not `m`.)
- **Never reuse a built-in name** (`list`, `sum`, `min`, `max`, `type` or `input`)

Exception in ML: the feature matrix is a capital `X` and the target is a lowercase `y`

Rewrite this code with good names. It computes the fraction of samples that are tumors.

```python
l = [0, 1, 1, 0, 1]
n = 0
for i in l:
    n = n + i
x = n / len(l)
```

In [19]:
labels = [0, 1, 1, 0, 1]
n_tumors = 0
for label in labels:
    n_tumors = n_tumors + label
tumor_fraction = n_tumors / len(labels)
tumor_fraction

0.6

## 1.3 Collections: list, tuple, dict, set

| Type | Looks like | Ordered | Changeable | Typical use |
| --- | --- | --- | --- | --- |
| `list` | `[1, 2, 3]` | yes | yes | a sequence of values |
| `tuple` | `(1, 2, 3)` | yes | no | a fixed group, like `(rows, cols)` |
| `dict` | `{"A": 1}` | by insertion | yes | look up a value by a key |
| `set` | `{1, 2, 3}` | no | yes | unique items, membership tests |

In [20]:
# indexing
genes = ["TP53", "BRCA1", "MYC", "GAPDH", "EGFR"]

print(genes[0], genes[-1])
print(genes[1:3])
print(genes[-2:])
print(genes[::2])

TP53 EGFR
['BRCA1', 'MYC']
['GAPDH', 'EGFR']
['TP53', 'MYC', 'EGFR']


In [21]:
shape = (28, 28)

In [22]:
codon_table = {"ATG": "Met", "TGG": "Trp", "TAA": "Stop"}
print(codon_table["ATG"])
codon_table["GGC"] = "Gly"
print(codon_table)

Met
{'ATG': 'Met', 'TGG': 'Trp', 'TAA': 'Stop', 'GGC': 'Gly'}


In [23]:
oncogenes = {"MYC", "EGFR", "KRAS"}
print("MYC" in oncogenes)
print(set(genes) & oncogenes)

True
{'MYC', 'EGFR'}


In [24]:
big_list = list(range(1_000_000))
big_set = set(big_list)

%timeit 999_999 in big_list
%timeit 999_999 in big_set

127 ms ± 24.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
646 ns ± 193 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


**Mutability trap.** Assigning a list to a new name does not copy it. Both names point to the *same* list.

In [25]:
a = [1, 2, 3]
b = a
b.append(4)
print("a =", a) 

a = [1, 2, 3, 4]


In [26]:
c = a.copy()
c.append(5)
print("a =", a, "| c =", c)

a = [1, 2, 3, 4] | c = [1, 2, 3, 4, 5]


## 1.4 Control flow

In [27]:
# if, elif, and else
expression = 7.3

if expression > 10:
    print("high")
elif expression > 5:
    print("medium")
else:
    print("low")

medium


In [28]:
# for with range: range(start, stop, step)
for i in range(0, 10, 3):
    print(i, end=" ")

0 3 6 9 

In [29]:
# enumerate: index and value together
for i, gene in enumerate(genes):
    print(i, gene)

0 TP53
1 BRCA1
2 MYC
3 GAPDH
4 EGFR


In [30]:
# zip: walk through two lists side by side
lengths = [393, 1863, 439, 335, 1210]   # protein lengths (amino acids)
for gene, length in zip(genes, lengths):
    print(f"{gene}: {length} aa")



TP53: 393 aa
BRCA1: 1863 aa
MYC: 439 aa
GAPDH: 335 aa
EGFR: 1210 aa


In [ ]:
# while: repeat until a condition becomes False
population = 1
generations = 0
while population < 1000:
    population *= 2
    generations += 1
print("Generations to reach 1000 cells:", generations)

Generations to reach 1000 cells: 10


## 1.5 List comprehensions

A compact way to build a list from a loop, optionally with a condition:

```python
[expression for item in iterable if condition]
```

In [32]:
squares = [x ** 2 for x in range(1, 6)]
print(squares)

even_squares = [x ** 2 for x in range(1, 11) if x % 2 == 0]
print(even_squares)

# Two loops: the left `for` is the outer loop
pairs = [(x, y) for x in range(1, 4) for y in range(1, 4) if x < y]
print(pairs)

[1, 4, 9, 16, 25]
[4, 16, 36, 64, 100]
[(1, 2), (1, 3), (2, 3)]


### ✏️ Exercise 1

1. Use a list comprehension to create a list `mynumbers` of all numbers of the form $x^y$, with $x = 1, \dots, 10$, $y = 2, \dots, 7$ and $y > x$.
2. Compute the sum of the square roots of these numbers and store it in `total`. (`np.sqrt` and `np.sum` work on lists.)

In [33]:
import numpy as np
mynumbers = [x ** y for y in range(2, 8) for x in range(1, 11) if y > x]
total = np.sum(np.sqrt(mynumbers))
print(len(mynumbers), "numbers, sum of square roots =", total)

21 numbers, sum of square roots = 1293.7511005743431


## 1.6 Functions

`def` creates a function. Arguments can have **default values**. Variables created inside a function are **local**: they disappear when the function returns.

In [34]:
def gc_content(sequence, as_percent=False):
    """Fraction of G and C bases in a DNA sequence."""
    sequence = sequence.upper()
    n_gc = sequence.count("G") + sequence.count("C")
    fraction = n_gc / len(sequence)
    if as_percent:
        return 100 * fraction
    return fraction

print(gc_content("ATGCGC"))
print(gc_content("ATGCGC", as_percent=True))

0.6666666666666666
66.66666666666666


### ✏️ Exercise 2

1. Write a function `my_minimum(v)` that returns the smallest entry of a vector **without** using built-ins such as `min` or `np.minimum`. Use a loop. (And don't call any variable `min`!)
2. Test it on a vector of 10 random integers between 1 and 100. Note that `rng.integers(1, 101, size=10)` excludes the upper bound, so this gives 1 to 100.

In [35]:
def my_minimum(v):
    smallest = float("inf")
    for element in v:
        if element < smallest:
            smallest = element
    return smallest

rng = np.random.default_rng(0)
test_vector = rng.integers(1, 101, size=10)
print(test_vector)
my_minimum(test_vector)

[86 64 52 27 31  5  8  2 18 82]


np.int64(2)

## 1.7 `*args` and `**kwargs`

- `*args` collects any number of **positional** arguments into a tuple.
- `**kwargs` collects any number of **keyword** arguments into a dict.

Examples:
- `plt.plot(x, y, color="r", linewidth=2)`
- `model.set_params(**params)`

In [36]:
def describe(*args, **kwargs):
    print("args   =", args)
    print("kwargs =", kwargs)

describe(1, 2, 3, color="red", size=10)

args   = (1, 2, 3)
kwargs = {'color': 'red', 'size': 10}


In [37]:
# Unpacking goes the other way: * spreads a list, ** spreads a dict
def make_label(gene, organism, unit="TPM"):
    return f"{gene} ({organism}), {unit}"

settings = {"organism": "human", "unit": "FPKM"}
print(make_label("TP53", **settings))
print(make_label(*["MYC", "mouse"]))

TP53 (human), FPKM
MYC (mouse), TPM


### ✏️ Write `mean_of(*numbers)` that returns the mean of any number of arguments, e.g. `mean_of(1, 2, 3)` gives `2.0`.

In [38]:
def mean_of(*numbers):
    return sum(numbers) / len(numbers)

## 1.8 `lambda`

A `lambda` is a tiny one-line function without a name. It is handy when a function wants another function as an argument, like `sorted(key=...)` here, or pandas `apply` next session.

In [39]:
# Sort genes by protein length, using zip to keep the pairs together
gene_lengths = list(zip(genes, lengths))
print(sorted(gene_lengths, key=lambda pair: pair[1]))

def by_length(pair):
    return pair[1]
print(sorted(gene_lengths, key=by_length))

[('GAPDH', 335), ('TP53', 393), ('MYC', 439), ('EGFR', 1210), ('BRCA1', 1863)]
[('GAPDH', 335), ('TP53', 393), ('MYC', 439), ('EGFR', 1210), ('BRCA1', 1863)]


## 1.9 Imports and f-strings

In [40]:
import math
from statistics import mean
import numpy as np               

gc = gc_content("ATGCGCAT")
print(f"GC content: {gc}")
print(f"GC content: {gc:.2f}")
print(f"sqrt(2) = {math.sqrt(2):.4f}, mean = {mean([1, 2, 3])}")

GC content: 0.5
GC content: 0.50
sqrt(2) = 1.4142, mean = 2


## 1.10 Errors: reading tracebacks and `try/except`

When something breaks, Python prints a **traceback**. Read it **from the bottom up**: the last line says *what* went wrong, and the lines above it say *where*.

In [41]:
# Remove the # from the last line to see a traceback, then read it bottom-up.
def average_expression(values):
    return sum(values) / len(values)

# average_expression([])   # ZeroDivisionError: division by zero

`try/except` lets you handle an error you **expect**. Catch the specific error type, never a bare `except:`. A bare `except` also hides the bugs you don't expect.

In [42]:
raw_values = ["3.2", "4.8", "NA", "5.1"]   # "NA" is common in real data files

parsed = []
for text in raw_values:
    try:
        parsed.append(float(text))
    except ValueError:
        parsed.append(None)

print(parsed)

[3.2, 4.8, None, 5.1]


### ✏️ Write `safe_ratio(a, b)` that returns `a / b`, or `None` if `b` is zero. Use `try/except` with the right error type.

In [43]:
def safe_ratio(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return None

## 1.11 Getting help yourself

Before asking anyone, try:

- `np.linspace?` in a notebook cell shows the docstring. `help(np.linspace)` does the same anywhere.
- Hover over a function, or press Tab after `np.`, to see what exists.
- Search the official docs (numpy.org, scikit-learn.org) and read a page in this order: **signature → parameters → returns → examples**. The examples at the bottom are often the fastest way in.

In [44]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000001F3326ECA60>
File:            c:\users\hossein\appdata\roaming\python\python310\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpo

---
# Part 2: NumPy



## 2.1 Why NumPy?

Python lists are flexible but slow for numbers. NumPy arrays store numbers in one block of memory and run operations in compiled code. That's called **vectorization**: operate on the whole array at once instead of looping.

In [45]:
values = list(range(1_000_000))
values_array = np.arange(1_000_000)

print("Python loop:")
%timeit sum(v * 2 for v in values)
print("NumPy:")
%timeit (values_array * 2).sum()

Python loop:


1.99 s ± 671 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
NumPy:
33.7 ms ± 4.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 2.2 Creating arrays

In [ ]:
print(np.array([1.5, 2.0, 3.5]))
print(np.zeros(4))
print(np.ones((2, 3)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[1.5 2.  3.5]
[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## 2.3 Shape, dimensions and type

- `shape`: the size along each axis, as a tuple
- `ndim`: the number of axes
- `dtype`: the type of every element (an array has one type)

In [47]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("shape:", matrix.shape)
print("ndim: ", matrix.ndim)
print("dtype:", matrix.dtype)

shape: (2, 3)
ndim:  2
dtype: int64


`reshape` changes the shape without changing the data. The total number of elements must stay the same.

In [48]:
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [49]:
matrix.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [50]:
matrix.ravel() # same as .reshape(-1)

array([1, 2, 3, 4, 5, 6])

> **Shape habit.** When something breaks, print `.shape` first. Most beginner ML bugs are shape mismatches: a `(100,)` vector where a `(100, 1)` column was expected, or features and samples swapped.

### ✏️ Your turn

Create `grid`: the numbers 0 to 19 arranged in 4 rows and 5 columns.

In [51]:
grid = np.arange(20).reshape(4, 5)
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 2.4 Element-wise operations and broadcasting

Arithmetic on arrays works **element by element**. No loop needed.

In [52]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
print(a * b)
print(a ** 2)
print(np.log(b))

[11 22 33]
[10 40 90]
[1 4 9]
[2.30258509 2.99573227 3.40119738]


**Broadcasting**: when shapes differ, NumPy stretches the smaller array to match, if the shapes are compatible. Compatible means that, comparing shapes from the right, each pair of sizes is equal or one of them is 1.

Our running example is a small gene-expression table: 6 samples (rows) × 4 genes (columns), with a label per sample (0 = healthy, 1 = tumor). This `X` / `y` layout is exactly what every ML model expects.

In [53]:
gene_names = np.array(["TP53", "BRCA1", "MYC", "GAPDH"])
X = np.array([
    [5.1, 2.0, 7.9, 10.2],
    [3.2, 1.1, 12.4, 10.0],
    [5.6, 2.3, 8.1, 9.8],
    [2.9, 0.8, 13.0, 10.4],
    [3.4, 1.0, 11.7, 10.1],
    [5.3, 2.2, 7.5, 9.9],
])
y = np.array([0, 1, 0, 1, 1, 0])
print("X:", X.shape, " y:", y.shape)

X_scaled = X * 2                     
gene_offsets = np.array([1, 0, -1, 0])
X_shifted = X + gene_offsets      
print(X_shifted[:2])

X: (6, 4)  y: (6,)
[[ 6.1  2.   6.9 10.2]
 [ 4.2  1.1 11.4 10. ]]


## 2.5 Indexing

### Slicing in 2D

`X[row, column]`. A `:` means "everything along this axis".

In [54]:
print(X[0, 2]) # sample 0, gene 2
print(X[0]) # first sample (a row): all 4 genes
print(X[:, 0]) # first gene (a column): all 6 samples
print(X[1:3, :2]) # samples 1-2, genes 0-1

7.9
[ 5.1  2.   7.9 10.2]
[5.1 3.2 5.6 2.9 3.4 5.3]
[[3.2 1.1]
 [5.6 2.3]]


### Boolean masks

A comparison gives an array of `True`/`False`. Using it as an index keeps only the `True` positions.

In [55]:
is_tumor = y == 1
print(is_tumor)
print(X[is_tumor]) # only tumor samples
print(X[:, 2][X[:, 2] > 10]) # MYC values above 10

[False  True False  True  True False]
[[ 3.2  1.1 12.4 10. ]
 [ 2.9  0.8 13.  10.4]
 [ 3.4  1.  11.7 10.1]]
[12.4 13.  11.7]


### Fancy indexing (with integer arrays)

Index with a list or array of positions to pick exactly those elements, in that order.

In [56]:
print(gene_names[[2, 0]]) # MYC, then TP53
print(X[[0, 5, 3]]) # samples 0, 5 and 3, in that order

['MYC' 'TP53']
[[ 5.1  2.   7.9 10.2]
 [ 5.3  2.2  7.5  9.9]
 [ 2.9  0.8 13.  10.4]]


**Shuffling** uses fancy indexing. Shuffle `X` and `y` with the **same** permutation so each sample keeps its label. A train/test split works like this underneath.

In [57]:
rng = np.random.default_rng(42)
idx = rng.permutation(len(y))
print("idx:", idx)

X_shuffled = X[idx]
y_shuffled = y[idx]
print(y_shuffled)

idx: [3 2 5 4 1 0]
[1 0 0 1 1 0]


## 2.6 `axis`

Reductions like `mean`, `sum` and `max` can work along one axis.

- `axis=0` goes **down the rows** and gives one value **per column** (per gene).
- `axis=1` goes **across the columns** and gives one value **per row** (per sample).

Rule of thumb: **the axis you name is the one that disappears.** `X` is `(6, 4)`; `X.mean(axis=0)` is `(4,)`.

In [58]:
X.mean()

np.float64(6.495833333333333)

In [59]:
X.mean(axis=0)

array([ 4.25      ,  1.56666667, 10.1       , 10.06666667])

In [60]:
X.mean(axis=1)

array([6.3  , 6.675, 6.45 , 6.775, 6.55 , 6.225])

In [61]:
X_centered = X - X.mean(axis=0)

In [ ]:
X_centered

### ✏️ Using a Boolean mask and `axis`, compute `tumor_means`: the mean expression **of each gene** across **tumor samples only**. Which gene changes most between healthy and tumor?

In [62]:
tumor_means = X[y == 1].mean(axis=0)
healthy_means = X[y == 0].mean(axis=0)
difference = tumor_means - healthy_means
print("tumor:  ", tumor_means)
print("healthy:", healthy_means)
print("biggest change:", gene_names[np.argmax(np.abs(difference))])

tumor:   [ 3.16666667  0.96666667 12.36666667 10.16666667]
healthy: [5.33333333 2.16666667 7.83333333 9.96666667]
biggest change: MYC


## 2.7 Random numbers

Use a **generator** with a **seed**. The same seed gives the same "random" numbers every time, so your results are reproducible.

In [63]:
rng = np.random.default_rng(seed=42)

print(rng.random(5)) # uniform on [0, 1)
print(rng.integers(1, 7, size=10)) # discrete uniform from 1 to 6 (dice)
print(rng.binomial(n=1, p=0.3, size=10)) # Bernoulli: 1 with probability 0.3
print(rng.choice(["hip", "hop"], size=5)) # pick from a list
print(rng.normal(loc=0, scale=1, size=3)) # normal distribution

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[4 6 5 5 5 5 4 1 6 3]
[0 1 0 1 0 0 0 0 1 0]
['hip' 'hop' 'hop' 'hip' 'hip']
[-0.15452948 -0.42832782 -0.35213355]


You'll also see the older style `np.random.rand(...)`, `np.random.seed(...)` in tutorials and on the exercise sheet. It still works. For new code, prefer `default_rng`.

### ✏️ Exercise 3

A common trick to generate 100 samples of a binary variable with probability 0.7 for `True` (and 0.3 for `False`) is:

```python
np.random.rand(100) <= 0.7
```

**Explain why this trick produces the desired result.** Write your answer in the cell below, then run the experiment after it.

*Explanation:* `np.random.rand(100)` draws 100 independent values $U$ from the uniform distribution on $[0, 1)$. For a uniform variable, the probability of landing in an interval equals the interval's length, so $P(U \le 0.7) = 0.7$. The element-wise comparison `<= 0.7` turns each draw into `True` with probability 0.7 and `False` with probability 0.3. That is exactly a Bernoulli(0.7) sample. Over 100 draws we expect about 70 `True` values, but the exact count varies because the sample is random.

### Further Reading:

- Hands-On Machine Learning with Scikit-Learn and PyTorch; Aurélien Géron
- Python Data Science Handbook: Essential Tools for Working with Data
- http://geeksforgeeks.org
- https://stackoverflow.com/